// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIDAgn1_9VR-ZvSBHdqk8iPsyAE-nl5hQ',
    appId: '1:822459913949:web:9f723a8659a44fbd5cad34',
    messagingSenderId: '822459913949',
    projectId: 'twople-619',
    authDomain: 'twople-619.firebaseapp.com',
    storageBucket: 'twople-619.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX-EYMt4_2FZqb1fOtcD6XIeJyaSHjyMQ',
    appId: '1:822459913949:android:6b2c13cf1f40b6725cad34',
    messagingSenderId: '822459913949',
    projectId: 'twople-619',
    storageBucket: 'twople-619.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdDaBKQW0L6Qxst_P0Z4Ixfx2MLholXis',
    appId: '1:822459913949:ios:f915d47e4c10f0465cad34',
    messagingSenderId: '822459913949',
    projectId: 'twople-619',
    storageBucket: 'twople-619.appspot.com',
    androidClientId: '822459913949-np01n6fbgt6v4s8iovsm4g3chf6j2l9l.apps.googleusercontent.com',
    iosClientId: '822459913949-2srgovqplvsnmon3qkoha5e8opeqv999.apps.googleusercontent.com',
    iosBundleId: 'com.example.twople',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdDaBKQW0L6Qxst_P0Z4Ixfx2MLholXis',
    appId: '1:822459913949:ios:f915d47e4c10f0465cad34',
    messagingSenderId: '822459913949',
    projectId: 'twople-619',
    storageBucket: 'twople-619.appspot.com',
    androidClientId: '822459913949-np01n6fbgt6v4s8iovsm4g3chf6j2l9l.apps.googleusercontent.com',
    iosClientId: '822459913949-2srgovqplvsnmon3qkoha5e8opeqv999.apps.googleusercontent.com',
    iosBundleId: 'com.example.twople',
  );
}
